#!/bin/bash

# gradebook-aliases.sh
# Shell script to set up convenient aliases for gradebook CLI

# First, determine the shell type and corresponding rc file
detect_shell() {
    local shell_name=$(basename "$SHELL")
    case "$shell_name" in
        "bash")
            echo "$HOME/.bashrc"
            ;;
        "zsh")
            echo "$HOME/.zshrc"
            ;;
        *)
            echo "Unsupported shell: $shell_name"
            exit 1
            ;;
    esac
}

# Function to add aliases to shell config
add_aliases() {
    local rc_file="$1"
    local temp_file=$(mktemp)

    # Create header for the aliases section
    cat << 'EOF' > "$temp_file"

# Gradebook CLI Aliases
# Generated by gradebook-aliases.sh

# Basic Commands
alias gb='gradebook'
alias gba='gradebook add'
alias gbr='gradebook remove'
alias gbv='gradebook view'
alias gbe='gradebook edit'
alias gbm='gradebook move'

# Adding Items
alias gbc='gradebook add course'
alias gbac='gradebook add category'
alias gbaa='gradebook add assignment'

# Viewing Commands
alias gbvc='gradebook view courses'
alias gbvs='gradebook view summary'
alias gbvd='gradebook view details'
alias gbvt='gradebook view trends'
alias gbvg='gradebook view distribution'  # grade distribution

# Export Commands
alias gbex='gradebook export course'
alias gbexa='gradebook export all'

# Utility Script Aliases
alias gbu='gradebook-utils.sh'
alias gbub='gradebook-utils.sh backup'
alias gbua='gradebook-utils.sh batch-add-assignments'
alias gbue='gradebook-utils.sh batch-export'
alias gbup='gradebook-utils.sh analyze-progress'
alias gbuv='gradebook-utils.sh validate'

# Quick Grade Entry
alias grade='gradebook add assignment'
alias grades='gradebook view summary'
alias graded='gradebook view details'

# Function to quickly add a grade with category inference
# Usage: quickgrade <course> <title> <earned> <max>
quickgrade() {
    if [ "$#" -ne 4 ]; then
        echo "Usage: quickgrade <course> <title> <earned> <max>"
        return 1
    fi

    # Get the most recently used category for the course
    local recent_category=$(gradebook view course "$1" | grep "Category:" | head -n 1 | awk '{print $2}')

    if [ -n "$recent_category" ]; then
        gradebook add assignment "$1" "$recent_category" "$2" "$4" "$3"
    else
        echo "Error: No recent category found for $1"
        return 1
    fi
}

# Function to show course progress
# Usage: progress <course_code>
progress() {
    if [ "$#" -ne 1 ]; then
        echo "Usage: progress <course_code>"
        return 1
    fi

    gradebook view details "$1"
    gradebook view trends "$1"
}

# Function to quickly export current grades
# Usage: export_grades [format]
export_grades() {
    local format="${1:-txt}"
    local date=$(date +%Y%m%d)
    local export_dir="$HOME/Documents/grades"

    mkdir -p "$export_dir"
    gradebook export all --format="$format" --output-dir="$export_dir/$date"
    echo "Grades exported to: $export_dir/$date"
}

EOF

    # Check if aliases section already exists
    if grep -q "# Gradebook CLI Aliases" "$rc_file"; then
        # Remove old section and add new one
        sed -i '/# Gradebook CLI Aliases/,/^$/d' "$rc_file"
    fi

    # Append new aliases to rc file
    cat "$temp_file" >> "$rc_file"
    rm "$temp_file"

    echo "Aliases added to $rc_file"
}

# Function to show available aliases
show_aliases() {
    cat << 'EOF'
Available Gradebook Aliases:

Basic Commands:
  gb        -> gradebook
  gba       -> gradebook add
  gbr       -> gradebook remove
  gbv       -> gradebook view
  gbe       -> gradebook edit
  gbm       -> gradebook move

Adding Items:
  gbc       -> gradebook add course
  gbac      -> gradebook add category
  gbaa      -> gradebook add assignment

Viewing Commands:
  gbvc      -> gradebook view courses
  gbvs      -> gradebook view summary
  gbvd      -> gradebook view details
  gbvt      -> gradebook view trends
  gbvg      -> gradebook view distribution

Export Commands:
  gbex      -> gradebook export course
  gbexa     -> gradebook export all

Utility Commands:
  gbu       -> gradebook-utils.sh
  gbub      -> gradebook-utils.sh backup
  gbua      -> gradebook-utils.sh batch-add-assignments
  gbue      -> gradebook-utils.sh batch-export
  gbup      -> gradebook-utils.sh analyze-progress
  gbuv      -> gradebook-utils.sh validate

Quick Commands:
  grade     -> gradebook add assignment
  grades    -> gradebook view summary
  graded    -> gradebook view details

Helper Functions:
  quickgrade <course> <title> <earned> <max>
  progress <course_code>
  export_grades [format]

Example Usage:
  gbc CHM343 "Organic Chemistry" "Fall 2024"
  gbaa CHM343 "Homework" "Lab 1" 100 95
  gbvd CHM343
  quickgrade CHM343 "Quiz 1" 95 100
  progress CHM343
  export_grades csv

Note: Restart your shell or run 'source ~/.bashrc' (or ~/.zshrc)
to enable these aliases.
EOF
}

# Main script logic
main() {
    case "$1" in
        --help|-h)
            show_aliases
            exit 0
            ;;
        --install|-i)
            rc_file=$(detect_shell)
            if [ $? -eq 0 ]; then
                add_aliases "$rc_file"
                echo "Aliases installed successfully!"
                echo "Run 'source $rc_file' or restart your shell to use the new aliases."
            fi
            ;;
        *)
            echo "Usage: $0 [--help|--install]"
            echo "  --help, -h     Show available aliases"
            echo "  --install, -i  Install aliases to shell config"
            exit 1
            ;;
    esac
}

# Execute main function
main "$@"